# Generated by Django 5.1.1 on 2024-10-20 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(default='Undefined', max_length=100)),
                ('description', models.TextField(default='')),
                ('release_date', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='Undefined.jpg', upload_to='games/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.CharField(blank=True, max_length=500)),
                ('already_played', models.ManyToManyField(blank=True, related_name='played_by', to='app.game')),
                ('favorite_list', models.ManyToManyField(blank=True, related_name='favorited_by', to='app.game')),
                ('playing_now', models.ManyToManyField(blank=True, related_name='being_played_by', to='app.game')),
                ('to_play', models.ManyToManyField(blank=True, related_name='will_be_played_by', to='app.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
