# Generated by Django 5.1.1 on 2024-10-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
