# Generated by Django 5.1.1 on 2024-09-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_user_already_played_alter_user_favorite_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='to_play',
            field=models.ManyToManyField(related_name='will_be_played_by', to='frontend.game'),
        ),
    ]
