# Generated by Django 5.1.1 on 2024-09-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='already_played',
            field=models.ManyToManyField(related_name='played_by', to='frontend.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_list',
            field=models.ManyToManyField(related_name='favorited_by', to='frontend.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='playing_now',
            field=models.ManyToManyField(related_name='being_played_by', to='frontend.game'),
        ),
        migrations.AlterField(
            model_name='user',
            name='to_play',
            field=models.ManyToManyField(related_name='will_be_played_play_by', to='frontend.game'),
        ),
    ]
