# Generated by Django 5.1.1 on 2024-09-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='most_played',
            new_name='already_played_count',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='most_liked',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='data_lancamento',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='nome',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='want_play',
            new_name='to_play_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genero',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='Undefined', max_length=100),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_description', models.CharField(max_length=500)),
                ('already_played', models.ManyToManyField(related_name='played_by', to='frontend.game')),
                ('favorite_list', models.ManyToManyField(related_name='faved_by', to='frontend.game')),
                ('to_play', models.ManyToManyField(related_name='will_be_played_by', to='frontend.game')),
            ],
        ),
    ]
