# Generated by Django 5.1.1 on 2024-09-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_most_played_game_already_played_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.TextField(default='Undefined'),
        ),
    ]
