# Generated by Django 5.1.1 on 2024-09-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_game_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image_url',
        ),
        migrations.AddField(
            model_name='game',
            name='image_path',
            field=models.ImageField(default='Undefined.jpg', upload_to='games/'),
        ),
    ]
