# Generated by Django 5.1.1 on 2024-09-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_alter_user_to_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
