# Generated by Django 5.1.1 on 2024-09-26 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_game_image_url_game_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='image_path',
            new_name='image',
        ),
    ]
